-- ===========================================
-- Migration 01: Add authentication columns
-- Run this against an existing EMRKS database that
-- was created from database_schema.sql.
-- ===========================================

USE EMRKS;

-- Patient login (FR-02)
ALTER TABLE Patient
    ADD COLUMN Username     VARCHAR(100) NULL UNIQUE,
    ADD COLUMN PasswordHash VARCHAR(255) NULL;

-- Staff login (FR-09, FR-17)
ALTER TABLE Staff
    ADD COLUMN Username     VARCHAR(100) NULL UNIQUE,
    ADD COLUMN PasswordHash VARCHAR(255) NULL;

-- Optional: seed an admin user so the app is usable on first run.
-- Replace the password hash with one generated by the app's Auth service.
-- The hash below is the BCrypt hash of the literal string "admin123" with
-- workFactor=11. Re-hash before any real deployment.
INSERT INTO Department (DepartmentName) VALUES ('Administration');

INSERT INTO Staff
    (FirstName, LastName, Role, PIN, AccessCardNumber, AuthorizationLevel,
     DepartmentID, Username, PasswordHash)
VALUES
    ('System', 'Admin', 'Admin', '0000', 'ADMIN-CARD-0000', 'Admin',
     LAST_INSERT_ID(), 'admin',
     '$2b$11$NscHxT9sOkYEz94NrJUiI.NUhIM/nDSRyRZp9FT/5BYJ5g44zikme');
